# See https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9"

services:
  # Backend Service
  back:
    container_name: tm-back
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      # Bind package directory with volume because speeding up.
      - go-packages:/go
      - ./backend/src:/work

volumes:
  go-packages:
